/**:
  ros__parameters:
    map_pcd_file: "/home/acclivis/avp_demo/data/JTA_R1.pcd"
    map_yaml_file: "/home/acclivis/avp_demo/data/autonomoustuff_parking_lot.yaml"
    # map_yaml_file: "/home/acclivis/avp_demo/data/Taltech_new.yaml"
    map_frame: "map"
    map_config:
      capacity: 1000000
      min_point:
        x: -1000.0
        y: -1000.0
        z: -3.0
      max_point:
        x: 1000.0
        y: 1000.0
        z: 3.0
      voxel_size:
        x: 3.5
        y: 3.5
        z: 3.5
    viz_map: True
